table Medidas
	lineageTag: 8ad7eb0c-1175-45c3-b63e-7f534ac09352

	measure '01 Quantidade Total' = ```
			
			SUM(fVendas[Quantidade])
			
			
			```
		formatString: #,0
		lineageTag: b23576fa-a06e-437d-b1b0-efedd0d75152

	measure '02 Frete Total' = ```
			
			SUM(fVendas[Vl.Frete])
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: a7aa4e2d-66eb-4c4a-89b0-e03c70261f3c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '03 Quantidade Máxima por Item' = ```
			
			MAX(fVendas[Quantidade])
			
			
			
			```
		formatString: 0
		lineageTag: 8acab0fa-e090-4bb9-a3e2-c80b27f05bd6

	measure '04 Qtde Média por Item de Venda' = ```
			
			AVERAGE(
			    fVendas[Quantidade]
			)
			
			```
		lineageTag: c405fcde-abbc-47cd-9719-f1a59897cbe9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SE Quantidade Mínima' = ```
			
			MIN(
			    fVendas[Quantidade]   
			)
			
			```
		formatString: 0
		lineageTag: a1170dd1-6f34-4375-b246-3b401116717e

	measure '05 Total Venda Bruto' = ```
			
			SUMX(
			    fVendas,
			    fVendas[Quantidade] * RELATED(dProduto[Valor Unitario])
			)
			
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 397b4749-45ed-4bf9-975b-1f63d23f57f3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '06 Média Bruta por Item' = ```
			
			AVERAGEX(
			    fVendas,
			    fVendas[Quantidade] * RELATED(dProduto[Valor Unitario])
			)
			
			```
		lineageTag: 9ff4e632-2793-4bb9-9a2a-c7ad193c4432

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '07 Total do Custo' = ```
			
			SUMX(
			    fVendas,
			    fVendas[Quantidade] * RELATED(dProduto[Custo Unitário])
			)
			
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 764c6e91-57ef-4dec-a9db-916d313cb4be

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '08 Custo Medio por Item' = ```
			
			AVERAGEX(
			    fVendas,
			    fVendas[Quantidade] * RELATED(dProduto[Custo Unitário])
			)
			
			
			```
		lineageTag: 40ed07e1-9b1a-4eac-b281-b609277f7bb2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '09 Máximo Item de Venda' = ```
			
			MAXX(
			    fVendas,
			    fVendas[Quantidade] * RELATED(dProduto[Valor Unitario])
			)
			
			```
		lineageTag: 57c6410f-b6e9-406d-a40a-076071b32018

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '10 Mínimo Item de Venda' =
			
			MINX(
			    fVendas,
			    fVendas[Quantidade] * RELATED(dProduto[Valor Unitario])
			)
		lineageTag: c675d2d0-2af0-4154-954e-551a8cb60d2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '11 Quantidade de Vendas' = ```
			
			DISTINCTCOUNT(
			    fVendas[idNota]
			)
			
			
			```
		formatString: #,0
		lineageTag: 6f96be5e-ea4b-4020-b686-a7533b3b9232

	measure '12 Quantidade de Itens de Venda' = ```
			
			COUNTROWS(
			    fVendas
			)
			
			
			
			```
		formatString: 0
		lineageTag: a308fc0c-7e9e-4e3f-a58a-55a621d4e0fd

	measure '13 Total do Desconto' =
			
			SUMX(
			    fVendas,
			    [05 Total Venda Bruto]
			        *
			    ( fVendas[Desconto] / 100)
			)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: aeb7a40b-ec06-4dd7-90ac-63b7d4c61ad4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '14 Receita Líquida' = ```
			
			var vTotalBruto = [05 Total Venda Bruto] 
			var vTotalDespesas = 
			( [07 Total do Custo] + [02 Frete Total] + [13 Total do Desconto] )
			
			RETURN
			
			vTotalBruto - vTotalDespesas
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 7e1108c2-c5e5-4ebb-bf6d-c213199fbbcb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '15 Margem de Lucro(%)' = ```
			
			DIVIDE(
			    [14 Receita Líquida],
			    [05 Total Venda Bruto],
			    0
			)
			
			
			```
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: c10bdaa6-3a7b-4d9a-9472-c866860e525d

	measure '16 Ticket Medio' = ```
			
			DIVIDE(
			    [05 Total Venda Bruto],
			    [11 Quantidade de Vendas],
			    0
			)
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a3709f56-4090-44fa-976d-a21fd3eb8af0

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '17 Quantidade de Clientes na Base' =
			
			COUNTROWS( dCliente )
		formatString: 0
		lineageTag: 83b26706-6b98-4554-942c-4f746ea25f57

	measure '18 Quantidade de Clientes Positivados' =
			
			DISTINCTCOUNT(
			    fVendas[Cliente]
			)
		formatString: 0
		lineageTag: a0f08dbf-bded-47a3-bbb8-be49ceb08920

	measure '19 Clientes nao Positivados' = ```
			
			COUNTROWS(
			    EXCEPT(
			        VALUES( dCliente[idCliente] ), --Clientes no geral
			        VALUES( fVendas[Cliente] )     --Clientes que compraram
			    )
			)
			
			```
		formatString: 0
		lineageTag: 5b4ddf99-a6d3-45bd-b644-7d08690ba485

	measure '20 America do Norte Vendas' = ```
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    dLocal[Continente] = "América do Norte"
			)
			
			```
		lineageTag: c764ae40-8310-4677-9476-e64977780511

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '21 America do Norte Clientes Positivados' =
			
			CALCULATE(
			    [18 Quantidade de Clientes Positivados],
			    dLocal[Continente] = "América do Norte"
			
			)
		formatString: 0
		lineageTag: f1b02660-199f-4df2-a82c-62a4a67b0cc3

	measure '22 America do Norte Quantidade de Vendas' =
			
			CALCULATE(
			    [11 Quantidade de Vendas],
			    dLocal[Continente] = "América do Norte"
			)
		formatString: 0
		lineageTag: 04c1d244-5b63-4be8-9b77-9dc5ceb906d4

	measure '23 America do Norte Receita Líquida' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    dLocal[Continente] = "América do Norte"
			)
		lineageTag: 50bc3dbf-baee-43ae-8964-329a4e3f3cb5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '24 Oceania Vendas' =
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    dLocal[Continente] = "Oceania"
			)
		lineageTag: 15595001-2912-4052-bbd5-719842a1162d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '25 Oceania Clientes Positivados' =
			
			CALCULATE(
			    [18 Quantidade de Clientes Positivados],
			    dLocal[Continente] = "Oceania"
			)
		formatString: 0
		lineageTag: 65426c4c-9688-420e-b7fe-42fb034d9c1a

	measure '26 Oceania Quantidade de Vendas' =
			
			CALCULATE(
			    [11 Quantidade de Vendas],
			    dLocal[Continente] = "Oceania"
			)
		formatString: 0
		lineageTag: 35249450-de86-4eec-9722-4c5299da97be

	measure '27 Oceania Receita Líquida' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    dLocal[Continente] = "Oceania"
			)
		lineageTag: 5a6d5372-6f78-4eb2-a694-71ca4a405de3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '28 America do Sul Vendas' =
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    dLocal[Continente] = "América do Sul"
			)
		lineageTag: 36782add-69e8-4063-abce-5fa7f93ba8ba

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '29 America do Sul Clientes Positivados' =
			
			CALCULATE(
			    [18 Quantidade de Clientes Positivados],
			    dLocal[Continente] = "América do Sul"
			)
		formatString: 0
		lineageTag: 5a276a03-ff8e-4575-8258-09c7e2c43e61

	measure '30 America do Sul Quantidade de Vendas' =
			
			CALCULATE(
			    [11 Quantidade de Vendas],
			    dLocal[Continente] = "América do Sul"
			)
		formatString: 0
		lineageTag: eff1449f-09e3-4a12-a3db-505b81121b73

	measure '31 America do Sul Receita Líquida' = ```
			
			 
			CALCULATE(
			    [14 Receita Líquida],
			    dLocal[Continente] = "América do Sul"
			)
			```
		lineageTag: 255dc35d-48c1-49c4-9dc5-1593db90ecec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '32 Europa Vendas' =
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    dLocal[Continente] = "Europa"
			)
		lineageTag: 33b39548-26aa-46ae-91b2-cd623658ed60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '33 Europa Clientes Positivados' =
			
			CALCULATE(
			    [18 Quantidade de Clientes Positivados],
			    dLocal[Continente] = "Europa"
			)
		formatString: 0
		lineageTag: d57a71ae-334d-4a71-8cdd-57ef104f421e

	measure '34 Europa Quantidade de Vendas' =
			
			CALCULATE(
			    [11 Quantidade de Vendas],
			    dLocal[Continente] = "Europa"
			)
		formatString: 0
		lineageTag: 788d47e0-0ea5-4144-8703-2251bef864ac

	measure '35 Europa Receita Líquida' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    dLocal[Continente] = "Europa"
			)
		lineageTag: 35535640-d166-40f9-a078-93fa095fe901

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '36 Classificacao do Produto(Receita)' =
			
			SWITCH(
			    TRUE(),
			    [14 Receita Líquida] > 4000000, "Excelente",
			    [14 Receita Líquida] > 3000000, "Muito Bom",
			    [14 Receita Líquida] > 2000000, "Bom",
			    [14 Receita Líquida] > 1000000, "Satisfatório",
			    [14 Receita Líquida] > 700000, "Regular",
			    [14 Receita Líquida] > 600000, "Avaliar",
			    [14 Receita Líquida] > 400000, "Atenção",
			    "Ruim"
			)
		lineageTag: c2c03d85-99cf-40ad-88fd-e98e75e5804d

		annotation PBI_FormatHint = {"isText":true}

	measure '37 Visao America do Norte' =
			
			SWITCH(
			    FIRSTNONBLANK(TbMedidas[Codigo], "BRT"),
			    "BRT", [20 America do Norte Vendas],
			    "QTC", [21 America do Norte Clientes Positivados],
			    "QTV", [22 America do Norte Quantidade de Vendas],
			    "LIQ", [23 America do Norte Receita Líquida]
			)
		lineageTag: 38d73e2e-c31f-4071-b093-e27afd8569c1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '38 Visao America do Sul' = ```
			
			SWITCH(
			    FIRSTNONBLANK( TbMedidas[Codigo], "BRT" ),
			    "BRT", [28 America do Sul Vendas],
			    "QTC", [29 America do Sul Clientes Positivados],
			    "QTV", [30 America do Sul Quantidade de Vendas],
			    "LIQ", [31 America do Sul Receita Líquida]
			)
			
			
			
			```
		lineageTag: 07978f24-43ee-4bd2-8d7c-a2b24186dbbe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '39 Visao Europa' =
			
			SWITCH(
			    FIRSTNONBLANK(TbMedidas[Codigo], "BRT"),
			    "BRT", [32 Europa Vendas],
			    "QTC", [33 Europa Clientes Positivados],
			    "QTV", [34 Europa Quantidade de Vendas],
			    "LIQ", [35 Europa Receita Líquida]
			)
		lineageTag: 079c309c-cd71-46df-b206-6d386131be3c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '40 Visao Oceania' =
			
			SWITCH(
			    FIRSTNONBLANK(TbMedidas[Codigo], "BRT"),
			    "BRT", [24 Oceania Vendas],
			    "QTC", [25 Oceania Clientes Positivados],
			    "QTV", [26 Oceania Quantidade de Vendas],
			    "LIQ", [27 Oceania Receita Líquida]
			)
		lineageTag: 62978bae-1209-499c-b1c6-301fe5410ad4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '41 - Top 1 Margem de Lucro(%)' = ```
			
			var TbAux =
			SUMMARIZE(
			    dLocal,
			    dLocal[País],
			    "Lucro (%)",
			    [15 Margem de Lucro(%)]
			)
			
			RETURN
			
			MAXX(
			    TbAux,
			    [Lucro (%)]
			)
			
			
			```
		lineageTag: 951cec3e-0bd0-4558-916a-ebabe3e29468

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '42 - Top 1 Lucro(%) America do Norte' = ```
			
			CALCULATE(
			    [41 - Top 1 Margem de Lucro(%)],
			    dLocal[Continente] = "América do Norte"
			)
			
			
			
			
			
			
			```
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: 81dc899a-fbf3-4b0c-a6dd-129a84ac3c6b

	measure '43 - Top 1 Lucro(%) Europa' = ```
			
			CALCULATE(
			    [41 - Top 1 Margem de Lucro(%)],
			    dLocal[Continente] = "Europa"
			)
			
			
			```
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: 0b56cd74-c878-4b15-ada3-cafbabdfcc76

	measure '44 - Top 1 Lucro(%) Oceania' =
			
			CALCULATE(
			    [41 - Top 1 Margem de Lucro(%)],
			    dLocal[Continente] = "Oceania"
			)
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: 1560826f-7000-4c74-938d-32ac28236769

	measure '45 - Top 1 Lucro(%) America do Sul' =
			
			CALCULATE(
			    [41 - Top 1 Margem de Lucro(%)],
			    dLocal[Continente] = "América do Sul"
			)
		formatString: 0.000%;-0.000%;0.000%
		lineageTag: ab1ab87c-d034-4b5f-b52d-628adea43855

	measure '46 Visao Geral' =
			
			SWITCH(
			    FIRSTNONBLANK( TbMedidas[Codigo], "BRT" ),
			    "BRT", [05 Total Venda Bruto],
			    "QTC", [18 Quantidade de Clientes Positivados],
			    "QTV", [11 Quantidade de Vendas],
			    "LIQ", [14 Receita Líquida]
			
			)
		lineageTag: e7662214-0b8b-4e82-8a47-9a3f897d363e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '47 Qtde Paises VALUES' = ```
			
			var TbValues = VALUES( dLocal[País] )
			RETURN
			
			COUNTROWS( TbValues )
			
			
			```
		formatString: 0
		lineageTag: 753c8771-19fc-468e-9670-87a8d67af3cc

	measure '48 Qtde Paises ALL' = ```
			
			var TbAll = ALL( dLocal[País] )
			
			RETURN
			
			COUNTROWS( TbAll )
			
			```
		formatString: 0
		lineageTag: 63abd4fb-6e4a-45af-a0cd-a8203be7cb2a

	measure '49 Faturamento Bruto Total' =
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    ALL( dVendedor )
			)
		lineageTag: 8cb08249-1d9e-4f0a-8e56-2f88d0687911

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '50 Valor Bruto(%)' =
			
			DIVIDE(
			    [05 Total Venda Bruto],
			    [49 Faturamento Bruto Total],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 68af5525-746b-45bd-aee2-e17459a9674d

	measure 'SE Receita Liquida ALL' = ```
			
			CALCULATE(
			    [14 Receita Líquida],
			    ALL(dLocal)
			)
			
			```
		lineageTag: 9823d980-4a89-475c-b5cd-a98d3eb5e4eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SE (%) Receita Liquida' =
			
			DIVIDE(
			    [14 Receita Líquida],
			    [SE Receita Liquida ALLSELECTED],
			    0
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 68b13f2a-1287-4ad7-9309-ef033aba39ce

	measure 'SE Receita Liquida ALLSELECTED' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    ALLSELECTED(dLocal)
			)
		lineageTag: d155d13c-700f-4bac-9414-62210181af4c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '51 Ranking Gerentes' = ```
			
			
			var TbGerentes = ALL(dVendedor[Gerente])
			
			RETURN
			
			RANKX(
			    TbGerentes,
			    [05 Total Venda Bruto]
			)
			
			```
		formatString: 0
		lineageTag: 9e835b1e-0259-4234-a19b-d3b9f8b3eeaf

	measure '52 Frete Clientes A' =
			
			SUMX(
			    FILTER(
			        fVendas,
			        RELATED(dCliente[Classificacao]) = "A"
			    )
			    ,
			    [02 Frete Total]
			)
		lineageTag: fe662796-4491-443d-957b-095ec3a08a67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '53 Faturamento TOP1' = ```
			
			
			var TbGerentes = ALL(dVendedor[Gerente])
			
			RETURN
			
			CALCULATE(
			    [05 Total Venda Bruto],
			
			   FILTER(
			        TbGerentes,
			        [51 Ranking Gerentes] = 1
			    ) 
			
			   -- dVendedor[Gerente] = "Carmem"
			)
			
			
			```
		lineageTag: 4ea77df9-b1b8-42d6-81ea-80d555fc6d44

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '54 Faturamento TOP2' = ```
			
			
			var TbGerentes = ALL(dVendedor[Gerente])
			
			RETURN
			
			CALCULATE(
			    [05 Total Venda Bruto],
			
			   FILTER(
			        TbGerentes,
			        [51 Ranking Gerentes] = 2
			    ) 
			
			)
			
			```
		lineageTag: 107c560b-44df-4ef4-ac44-01dced33e18a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '55 Faturamento TOP3' = ```
			
			
			var TbGerentes = ALL(dVendedor[Gerente])
			
			RETURN
			
			CALCULATE(
			    [05 Total Venda Bruto],
			
			   FILTER(
			        TbGerentes,
			        [51 Ranking Gerentes] = 3
			    ) 
			
			)
			```
		lineageTag: aef7a442-70d6-49e7-a8cc-4d1d366781cc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'SE Gerente Top 2' = ```
			
			 
			 FILTER(
			        ALL( dVendedor[Gerente] ),
			        [51 Ranking Gerentes] = 2
			    ) 
			```
		lineageTag: 4fc67e48-64ff-4257-9c16-3cec3907e588

		annotation PBI_FormatHint = {"isText":true}

	measure '56 Rank URL Gerente' = ```
			
			RANKX(
			    ALL( dVendedor[URL Gerente] ),
			    [05 Total Venda Bruto]
			)
			
			```
		formatString: 0
		lineageTag: 46011bee-2e62-41ac-83a8-18c2b72ae28c

	measure '57 Vendas Ano Atual' = ```
			
			var AnoAtual = 
			MAX(
			    dCalendario[Ano]
			)
			
			RETURN 
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    dCalendario[Ano] = AnoAtual
			)
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 835a4b64-6699-4384-b468-6ed4e2e3da01

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '58 Meta do Ano' = ```
			
			
			var AnoAtual = MAX( dCalendario[Ano] )
			
			RETURN
			
			CALCULATE(
			    SUM( fMetas[Meta] ),
			    dCalendario[Ano] = AnoAtual
			)
			
			
			
			```
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: 01b4629b-f5f5-4922-b11e-b4b59e618602

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '59 Variacao da Meta' = ```
			
			[57 Vendas Ano Atual] - [58 Meta do Ano]
			
			```
		lineageTag: 8975db09-57c2-4ae3-8f8b-0c4e0beb7107

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '60 Variacao da Meta(%)' = ```
			
			DIVIDE(
			    [59 Variacao da Meta], -- (VENDAS - META)
			    [58 Meta do Ano], --META -> RESULTADO %
			    0
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8c5a0041-43f3-403c-a09b-5c9e96060dee

	measure '61 Vendas Ano Anterior' =
			
			VAR VVendas =
			CALCULATE(
			    [57 Vendas Ano Atual],
			    DATEADD( dCalendario[Data], -1, YEAR)
			)
			
			RETURN
			
			IF(ISBLANK( VVendas ), 0, VVendas)
		formatString: "R$"\ #,0;-"R$"\ #,0;"R$"\ #,0
		lineageTag: e3b59021-a5e3-4ce4-8120-0453b82eceb3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '62 Variacao Faturamento(%)' =
			
			
			VAR VVariacao =
			DIVIDE(
			    [57 Vendas Ano Atual] - [61 Vendas Ano Anterior],
			    [61 Vendas Ano Anterior],
			    BLANK()
			)
			
			RETURN
			
			IF( ISBLANK( VVariacao ), 0, VVariacao )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f3823772-714a-4473-b0b0-500efd40a516

	measure 'SE Ano Selecionado' =
			
			VAR VAno = SELECTEDVALUE(
			    dCalendario[Ano]
			)
			
			RETURN
			
			IF( ISBLANK( VAno ), MAX(dCalendario[Ano]), VAno )
		formatString: 0
		lineageTag: 211246ff-4ff0-4b28-bc26-015eafb4deab

	measure 'SE Ano Anterior' = ```
			
			[SE Ano Selecionado] - 1
			
			```
		formatString: 0
		lineageTag: 3c657eda-fa1f-4b52-bae1-9955f318a11d

	measure '63 Total Faturamento Bruto' =
			
			CALCULATE(
			    [05 Total Venda Bruto],
			    USERELATIONSHIP(
			        fVendas[Data de Faturamento],
			        dCalendario[Data]
			    )
			) * -1
		formatString: "R$"\ #,0.00;  "R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 745bb29e-5636-4f4e-88e1-9db35be6b154

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Teste Receita Líquida PM' = ```
			
			CALCULATE(
			    [14 Receita Líquida],
			    DATEADD(dCalendario[Data], -1, YEAR)
			)
			
			```
		lineageTag: 8562aa10-f43f-43bc-8ebe-e979e507f996

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '64 Receita Líquida PY' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    SAMEPERIODLASTYEAR(dCalendario[Data])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 8abbba9f-e783-4675-a268-945f0af1cc4c

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '65 Receita Líquida YoY' = ```
			
			[14 Receita Líquida] - [64 Receita Líquida PY]
			
			
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: fc69e43e-e3be-4604-bc3a-17d86e574ffb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '66 Receita Líquida YoY(%)' = ```
			
			DIVIDE(
			    [65 Receita Líquida YoY],
			    [64 Receita Líquida PY],
			    0
			)
			
			
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4ca9c035-9411-4af9-b7ef-920df91270a4

	measure '67 Receita Líquida Total Geral' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    ALL(dCalendario)
			)
		lineageTag: 6cb750ea-2399-4cd3-b999-f56c793be5bc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '68 variacao Receita Líquida Total(%)' =
			
			DIVIDE(
			    [14 Receita Líquida],
			    [67 Receita Líquida Total Geral],
			    BLANK()
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 866560ec-463f-479b-a1a2-d0cd3fd587d4

	measure '69 Receita Líquida Total do Ano' = ```
			
			CALCULATE(
			    [14 Receita Líquida],
			    ALL(dCalendario[Mês])
			)
			
			
			```
		lineageTag: acefadd2-9a8e-43c2-856b-d74f3a405970

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '70 variacao Receita Líquida Total no Ano' = ```
			
			[14 Receita Líquida] / [69 Receita Líquida Total do Ano]
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4f0467f9-1f94-4d5e-89a8-ac9a904c9c53

	measure '71 Receita Líquida Acumulada' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    DATESYTD(dCalendario[Data])
			)
		lineageTag: e4d420a5-ac65-4513-a570-d7015e4c66e7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '72 Receita Anual Líquida Acumulada' =
			
			TOTALYTD(
			    [14 Receita Líquida],
			    dCalendario[Data]
			)
		lineageTag: 278a121c-f1ec-42d7-a5ad-262896afd532

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '73 Receita Líquida Acumulada' = ```
			
			CALCULATE(
			    [14 Receita Líquida],
			    
			    DATESBETWEEN(
			        dCalendario[Data],
			        BLANK(),
			        MAX(dCalendario[Data])
			    )
			)
			
			```
		lineageTag: 001e4157-0cfe-4459-a9b7-86b9fb3cb748

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '74 Acumulado Móvel 3M' =
			
			CALCULATE(
			    [14 Receita Líquida],
			    DATESINPERIOD(
			        dCalendario[Data],
			        MAX(dCalendario[Data]),
			        -3,
			        MONTH
			    )
			)
		lineageTag: 3ec94b8a-b138-45ce-9209-5fd257906d21

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '75 SIM Venda Bruta' = ```
			
			[05 Total Venda Bruto] *
			( 1 + [SIMQuantidade Valor] ) * ( 1 + [SIMPreço Valor] )
			
			
			
			```
		lineageTag: eeea8815-d650-4333-a57e-5f32cc6cf5a4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '76 SIM Variacao Venda' = ```
			
			
			
			Var Variacao=[75 SIM Venda Bruta] - [05 Total Venda Bruto]
			
			RETURN
			
			IF.EAGER(Variacao<>0, Variacao, BLANK())
			
			
			```
		formatString: 0.00
		lineageTag: fe200560-aeb1-454f-b494-c1d51958734c

	measure '77 SIM Custos' = ```
			
			[07 Total do Custo] *
			( 1 + [SIMQuantidade Valor] ) * ( 1 + [SIMCustos Valor] )
			
			
			```
		lineageTag: 8abce706-8f49-41d4-be47-c38ffa16bc8a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '78 SIM Variacao Custos' = ```
			
			[77 SIM Custos] - [07 Total do Custo]
			
			
			```
		lineageTag: 6e8c3077-a61d-44c8-b7f0-4d000927509b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '79 SIM Frete' =
			
			[02 Frete Total] * ( 1 + [SIMFrete Valor] )
		lineageTag: cd0de373-6b85-40e0-8e70-68e14c676f18

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '80 SIM variacao Frete' =
			
			[79 SIM Frete] - [02 Frete Total]
		lineageTag: dd9ec114-ddc3-41f2-ab0a-48bc82e14549

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '81 SIM Desconto' = ```
			
			[13 Total do Desconto] * ( 1 + [SIMDesconto Valor] )
			
			
			
			```
		lineageTag: be36b8dd-6c8e-48c1-8d40-f9807ade3093

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '82 SIM Variacao Desconto' = ```
			
			[81 SIM Desconto] - [13 Total do Desconto]
			
			```
		lineageTag: da4e3707-f128-464b-8bf7-f7b18e1b89ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '83 SIM Receita Líquida' = ```
			
			[75 SIM Venda Bruta] -
			( [79 SIM Frete] + [77 SIM Custos] + [81 SIM Desconto] )
			
			
			
			```
		lineageTag: ee86a03a-213d-4af1-8f1f-9d1686832ea9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '84 SIM Variacao da Receita' =
			
			[83 SIM Receita Líquida] - [14 Receita Líquida]
		lineageTag: 91f2a819-6a85-425f-abcf-25125b0b0000

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '85 SIM Margem de Lucro (%)' = ```
			
			DIVIDE(
			    [83 SIM Receita Líquida],
			    [75 SIM Venda Bruta],
			    0
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 428e3189-761a-4b47-9edf-7d4b5ecb7406

	measure '86 SIM Variacao Receita (%)' =
			
			DIVIDE(
			    [83 SIM Receita Líquida],
			    ABS([14 Receita Líquida]),
			    0
			) - 1
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a2ba2832-92bd-48cd-8843-3e8505bc5ff0

	measure '87 KPI Receita' =
			
			SWITCH(
			    TRUE(),
			    [86 SIM Variacao Receita (%)] > 0.000000001, "🟢" ,
			    [86 SIM Variacao Receita (%)] < -0.000000001, "🔴" ,
			    "🟣"
			)
		lineageTag: 6861b973-1d7a-411e-be03-3cd953bbc5c7

		annotation PBI_FormatHint = {"isText":true}

	measure '88 Cross Número de Vendas' = ```
			
			VAR TbVendas = VALUES(fVendas[idNota])
			
			VAR TbVendasAux =
			CALCULATETABLE(
			    VALUES(fVendas[idNota]),
			    ALL(dProduto),
			    USERELATIONSHIP(fVendas[Produto],'Aux Produto'[IdProduto])
			)
			
			VAR TbInter = INTERSECT( TbVendas, TbVendasAux )
			VAR vResultado = COUNTROWS( TbInter )
			
			RETURN
			
			IF(
			    SELECTEDVALUE( dProduto[Sub-Categoria] ) <> SELECTEDVALUE('Aux Produto'[Sub-Categoria] ),
			    vResultado,
			    BLANK()
			)
			
			
			
			```
		formatString: 0
		lineageTag: 81d18b1d-50e7-4f2c-96e2-0fd71de4eb5d

	measure '89 Cross Variacao (%)' = ```
			
			DIVIDE(
			    [88 Cross Número de Vendas],
			    [11 Quantidade de Vendas],
			    0
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: e8d25120-eb2d-42c8-8525-a99e492ed386

	partition Medidas-f7a047ee-ed0a-4eda-bd97-dbc9cd8f657b = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

