table SIMCustos
	lineageTag: c846ba12-774b-41b7-8f4a-1a7966dfa158

	measure 'SIMCustos Valor' = SELECTEDVALUE('SIMCustos'[SIMCustos], 0)
		formatString: 0%;-0%;0%
		lineageTag: 83849a1d-aa92-47a5-898c-b26207c44569

	column SIMCustos
		formatString: 0%;-0%;0%
		lineageTag: 612a0754-7701-4a4f-a6bd-4e13a4cac95d
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition SIMCustos-b86c6b72-eca3-44aa-a69d-9031dc06540f = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.02)

	annotation PBI_Id = 0368c97cb88045b3adbe81440fe654f8

