table SIMDesconto
	lineageTag: b89938cb-9dcc-4ae6-b0be-d1c66aad1aa7

	measure 'SIMDesconto Valor' = SELECTEDVALUE('SIMDesconto'[SIMDesconto], 0)
		formatString: 0%;-0%;0%
		lineageTag: cf0fee3b-c756-4157-933f-48dac4f15180

	column SIMDesconto
		formatString: 0%;-0%;0%
		lineageTag: f23f92a4-4da1-4c81-960e-c518c06689d6
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition SIMDesconto-dd030531-3d2a-42b4-bf69-1e0208345f26 = calculated
		mode: import
		source = GENERATESERIES(-1, 1, 0.02)

	annotation PBI_Id = 10442cb7da834b4f952c6d233e25876d

