table dCalendario
	lineageTag: 4fd1cae5-3e7d-4dcb-bf28-ecae532acead

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: 645b0649-92b9-4f9d-babb-8e0dbbea9476
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 74c2787b-3ed3-4948-9f30-39a33b3dad35
			defaultHierarchy: LocalDateTable_6fe11618-1b62-4329-b506-c5383d58b46d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: cadd759a-577a-45c3-9f32-24708fdb0b1c
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 2ccc2d43-e795-499e-87b7-e012da17ccec
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 06a1225f-151c-4fe1-aa46-5986118d25d6
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 464123d2-da72-4ba7-95be-8cd857cdea3d
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 3df9fcb1-9f51-4c8a-a38e-341f256c9f97
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: 976bf7af-acf5-4195-a2b5-72fbd1b3d2f9
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column 'ano mes num'
		dataType: int64
		formatString: 0
		lineageTag: a2193c6c-3bfb-4c2b-a5ca-2f800e6db4e0
		summarizeBy: sum
		sourceColumn: ano mes num

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source =
				let
				    dCalendario = let
				
				    /*  CRIANDO AS VARIAVEIS */
				
				    Tabela = List.Buffer( interacoes[Data] ),
				
				    MinDate = List.Min( Tabela ),
				    MaxDate = List.Max( Tabela ),
				
				    MaxYear = Date.Year( MaxDate ),
				    MinYear = Date.Year( MinDate ),
				    InitialDate = #date(  MinYear ,  1  ,  1  ),
				    EndDate = #date(  MaxYear ,  12  ,  31  ),
				
				    Duration = Duration.Days(  EndDate - InitialDate ) + 1,
				
				
				
				    Fonte = List.Dates(InitialDate , Duration, #duration(1, 0, 0, 0)),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Convertido para Tabela",{{"Column1", "Data"}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"Data", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Mês Inserido" = Table.AddColumn(#"Nome do Mês Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Mês Inserido", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Dia Inserido", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    #"Prefixo Adicionado" = Table.TransformColumns(#"Trimestre Inserido", {{"Trimestre", each "T" & Text.From(_, "pt-BR"), type text}}),
				    #"Coluna Personalizada Adicionada" = Table.AddColumn(#"Prefixo Adicionado", "Mes e Ano", each Text.Combine({Text.Start(Text.Proper([Nome do Mês]), 3), " ", Text.From([Ano], "pt-BR")}), type text),
				    #"Coluna Personalizada Adicionada1" = Table.AddColumn(#"Coluna Personalizada Adicionada", "Ano Mes Num", each Text.Combine({Text.From([Ano], "pt-BR"), Text.PadStart(Text.From([Mês], "pt-BR"), 2, "0")}), type text),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Personalizada Adicionada1",{{"Ano Mes Num", Int64.Type}})
				
				in
				    #"Tipo Alterado",
				    #"Tipo Alterado" = Table.TransformColumnTypes(dCalendario,{{"Data", type date}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data]), Int64.Type),
				    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
				    #"Dia Inserido" = Table.AddColumn(#"Mês Inserido", "Dia", each Date.Day([Data]), Int64.Type),
				    #"Nome do Dia Inserido" = Table.AddColumn(#"Dia Inserido", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
				    #"Trimestre Inserido" = Table.AddColumn(#"Nome do Dia Inserido", "Trimestre", each Date.QuarterOfYear([Data]), Int64.Type),
				    #"Prefixo Adicionado" = Table.TransformColumns(#"Trimestre Inserido", {{"Trimestre", each "T" & Text.From(_, "pt-BR"), type text}}),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Prefixo Adicionado", "Nome do Mês", each Date.MonthName([Data]), type text),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Nome do Mês Inserido",{"Data", "Ano", "Mês", "Nome do Mês", "Dia", "Nome do Dia", "Trimestre"}),
				    #"Adição Inserida" = Table.AddColumn(#"Colunas Reordenadas", "ano mes num", each [Mês] + 202500, type number),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Adição Inserida",{{"ano mes num", Int64.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

