table 'Fclientes nps'
	lineageTag: d054f3c3-2c0e-4579-8319-30662e5b7192

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 4d4c06e3-e836-4d3d-986b-b1c0dfc9f918
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column 'Primeiro Nome'
		dataType: string
		lineageTag: 4d8c0a6a-659a-42bd-b37c-7be6a5e61ca5
		summarizeBy: none
		sourceColumn: Primeiro Nome

		annotation SummarizationSetBy = Automatic

	column Sobrenome
		dataType: string
		lineageTag: 4a6cd4c7-599d-4996-858b-0d7a0ba7d578
		summarizeBy: none
		sourceColumn: Sobrenome

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: bbc4ab73-bc21-4868-8646-c05125b9571f
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column 'Data de Entrada'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 237080a7-5377-42ae-ab7a-54df6c8f7dcf
		summarizeBy: none
		sourceColumn: Data de Entrada

		variation Variation
			isDefault
			relationship: dbd8c18b-b432-4495-9b60-ce03edba0fbd
			defaultHierarchy: LocalDateTable_5c534e54-e90e-417d-8234-fc6201e37d1b.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Última Pontuação NPS (0-10)'
		dataType: int64
		formatString: 0
		lineageTag: 068216c9-7905-40eb-8b6e-f0b6e9d3c099
		summarizeBy: sum
		sourceColumn: Última Pontuação NPS (0-10)

		annotation SummarizationSetBy = Automatic

	column 'Categoria NPS'
		dataType: string
		lineageTag: 99e9bec1-b458-435e-96b7-8e4f6045d092
		summarizeBy: none
		sourceColumn: Categoria NPS

		annotation SummarizationSetBy = Automatic

	column Estado
		dataType: string
		lineageTag: e85f2d1b-a4f9-4d1c-9e61-baf7843ba464
		summarizeBy: none
		sourceColumn: Estado

		annotation SummarizationSetBy = Automatic

	column Município
		dataType: string
		lineageTag: 963a26ff-886b-4060-a3cb-bf91198299f5
		summarizeBy: none
		sourceColumn: Município

		annotation SummarizationSetBy = Automatic

	partition 'Fclientes nps' = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\home\OneDrive\Desktop\projetos\customer success\clientes nps.csv"),[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"CustomerID", Int64.Type}, {"Primeiro Nome", type text}, {"Sobrenome", type text}, {"Email", type text}, {"Data de Entrada", type date}, {"Última Pontuação NPS (0-10)", Int64.Type}, {"Categoria NPS", type text}, {"Estado", type text}, {"Município", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

