table Fpesquisa
	lineageTag: b3888cdb-9a2c-403b-8b61-7b1a34d476b2

	column SurveyID
		dataType: int64
		formatString: 0
		lineageTag: b4b4ccd7-2de7-4b0e-818e-69b2961f3505
		summarizeBy: count
		sourceColumn: SurveyID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 77f8e183-fc18-44f8-b3e4-6a4f598e017c
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column InteractionID
		dataType: int64
		formatString: 0
		lineageTag: ffeca646-e5c1-4d0a-af93-5589a055b6c8
		summarizeBy: count
		sourceColumn: InteractionID

		annotation SummarizationSetBy = Automatic

	column MetricType
		dataType: string
		lineageTag: 8c517332-9c59-485f-9ce0-361d4cfb7e75
		summarizeBy: none
		sourceColumn: MetricType

		annotation SummarizationSetBy = Automatic

	column Score
		dataType: int64
		formatString: 0
		lineageTag: b7f9d60a-72dc-49cb-93a7-b755776fd7e3
		summarizeBy: sum
		sourceColumn: Score

		annotation SummarizationSetBy = Automatic

	column 'Scale (Max)'
		dataType: int64
		formatString: 0
		lineageTag: 2992679a-3205-465d-b8c0-b83a5a85f20c
		summarizeBy: sum
		sourceColumn: Scale (Max)

		annotation SummarizationSetBy = Automatic

	column Feedback
		dataType: string
		lineageTag: 9a163a33-a675-46b7-a406-23be48ec7c7d
		summarizeBy: none
		sourceColumn: Feedback

		annotation SummarizationSetBy = Automatic

	partition Fpesquisa = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\home\OneDrive\Desktop\projetos\customer success\pesquisa.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"SurveyID", Int64.Type}, {"CustomerID", Int64.Type}, {"InteractionID", Int64.Type}, {"MetricType", type text}, {"Score", Int64.Type}, {"Scale (Max)", Int64.Type}, {"Feedback", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

