table interacoes
	lineageTag: f66378a7-ea22-4aa1-86e9-70488f44b7aa

	column InteractionID
		dataType: int64
		formatString: 0
		lineageTag: ac921562-3059-42e2-a936-3c5ecaa86705
		summarizeBy: count
		sourceColumn: InteractionID

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 728516e7-e0bb-49f8-9c12-28c524d60b38
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Interação'
		dataType: string
		lineageTag: fe83cd3a-fbb0-4062-8620-7d84d6f12e6e
		summarizeBy: none
		sourceColumn: Tipo de Interação

		annotation SummarizationSetBy = Automatic

	column Data
		dataType: dateTime
		formatString: Long Date
		lineageTag: cb94ff1e-5fb1-4906-a80f-95445a5f2b66
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Canal
		dataType: string
		lineageTag: 8ce3ab27-8c3f-418e-8014-6c83f8b62d7e
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column 'Duração (min)'
		dataType: int64
		formatString: 0
		lineageTag: cdb8579e-2cc2-4151-9e47-d20d46b642f8
		summarizeBy: sum
		sourceColumn: Duração (min)

		annotation SummarizationSetBy = Automatic

	partition interacoes = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\home\OneDrive\Desktop\projetos\customer success\interacoes.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"InteractionID", Int64.Type}, {"CustomerID", Int64.Type}, {"Tipo de Interação", type text}, {"Data", type date}, {"Canal", type text}, {"Duração (min)", Int64.Type}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each true)
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

