table Medidas
	lineageTag: 7ff05a7a-9d6d-4485-8189-ff13ec10e34a

	measure '04 % Detratores' = DIVIDE([03 Qtde de Detratores],[01 Qtde de Clientes NPS] ,0)
		lineageTag: 3fb673b5-1ce7-4fa2-9003-5d657f023b05

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '05 % Promotores' = DIVIDE([02 Qtde Promotores],[01 Qtde de Clientes NPS] ,0)
		lineageTag: 0e3d36b3-f58c-47cc-9083-f31d44478a9b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '06 NPS' = ```
			(
			    [05 % Promotores] - 
			    [04 % Detratores]
			) * 100
			```
		lineageTag: 31cf7261-311c-435a-8420-5d66e746e618

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '01 Qtde de Clientes NPS' = DISTINCTCOUNT('Fclientes nps'[CustomerID])
		formatString: 0
		lineageTag: cbc17a87-c1a3-48d8-8ba6-285c666007bd

	measure '03 Qtde de Detratores' = CALCULATE([01 Qtde de Clientes NPS],'Fclientes nps'[Categoria NPS]="Detrator")
		formatString: 0
		lineageTag: 13a90c02-177a-46c5-a060-25ab1e02bd03

	measure '02 Qtde Promotores' = CALCULATE([01 Qtde de Clientes NPS],'Fclientes nps'[Categoria NPS]="Promotor")
		formatString: 0
		lineageTag: 647b5cfe-b8a8-4c09-bba0-23f596f37938

	measure '08 Qtde de Pesquisa CES' = CALCULATE([07 Qtde de Clientes Pesquisa],Fpesquisa[MetricType]="CES")
		formatString: 0
		lineageTag: 510ba2c0-8c87-4642-aa64-d41c4983cfe0

	measure '10 CES' = DIVIDE([09 CES Notas],[08 Qtde de Pesquisa CES])
		formatString: 0.00
		lineageTag: 337a16a6-a228-4836-bc5d-6cfd4e96fd21

	measure '09 CES Notas' = CALCULATE(SUM(Fpesquisa[Score]),Fpesquisa[MetricType]="CES")
		formatString: 0
		lineageTag: 4084e003-93a6-45b2-8162-fad20ab819d8

	measure '07 Qtde de Clientes Pesquisa' = DISTINCTCOUNT(Fpesquisa[CustomerID])
		formatString: 0
		lineageTag: 9ad3179d-a38b-4b57-8cc4-ade34d41e3ce

	measure '11 Qtde de Pesquisa CSAT' = CALCULATE([07 Qtde de Clientes Pesquisa],Fpesquisa[MetricType]="CSAT")
		formatString: 0
		lineageTag: 1f7ff64f-a8e9-4d9a-9be4-dbada1975d21

	measure '12 CSAT Notas' = CALCULATE(SUM(Fpesquisa[Score]),Fpesquisa[MetricType]="CSAT")
		formatString: 0
		lineageTag: ad0ea3fd-8ac1-4ecb-ba61-456256a2c889

	measure '13 CSAT' = DIVIDE([12 CSAT Notas],[11 Qtde de Pesquisa CSAT])
		lineageTag: 3a8c25ce-af4a-4545-bf1d-b578eaa7ac36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '14 % CSAT' = DIVIDE([15 Csat satisfeitos],[11 Qtde de Pesquisa CSAT])
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 518deb03-2158-4bd2-a4d2-9f41f53e4058

	measure '15 Csat satisfeitos' = CALCULATE([11 Qtde de Pesquisa CSAT],Fpesquisa[Score]>=4)
		formatString: 0
		lineageTag: eb020965-9f2f-4041-9126-a4516cdbcd1f

	partition Medidas = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Coluna 1"})
				in
				    #"Colunas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

