table 'pesquisa de nps'
	lineageTag: 3f416ff3-031a-4e27-9ae0-8a9d278d91b4

	column 'ID Pesquisa NPS'
		dataType: int64
		formatString: 0
		lineageTag: a9ac0fbe-38b8-4c70-8049-327a7dfb18fe
		summarizeBy: sum
		sourceColumn: ID Pesquisa NPS

		annotation SummarizationSetBy = Automatic

	column 'ID Cliente'
		dataType: int64
		formatString: 0
		lineageTag: 9b3b95d2-b673-4b15-8c2d-cb14ff598f44
		summarizeBy: none
		sourceColumn: ID Cliente

		annotation SummarizationSetBy = Automatic

	column 'Data da Pesquisa'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c4fc4735-359c-4a8e-bbcd-e949685b0800
		summarizeBy: none
		sourceColumn: Data da Pesquisa

		variation Variation
			isDefault
			relationship: 4cacf529-3cd7-4806-8925-91f0cba8ca33
			defaultHierarchy: LocalDateTable_463625a3-2b58-4ab1-87f9-8d449537f3fa.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Pontuacao NPS (0-10)'
		dataType: int64
		formatString: 0
		lineageTag: 4dcb8122-5660-4367-8a36-7d1ff804e85a
		summarizeBy: sum
		sourceColumn: Pontuacao NPS (0-10)

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 837cb524-c988-48fb-9fb7-3157bd739bea
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 2e3aa92b-2cca-45ba-9df7-f935d805541a
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: fdb933bd-bb66-4b4d-ac7f-11c4601238e9
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: string
		lineageTag: ee7b11fd-201d-4134-84ae-a286ae10a311
		summarizeBy: none
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Nome do Mês'
		dataType: string
		lineageTag: 616c3a73-36dc-482f-9dd2-22a0c839e80e
		summarizeBy: none
		sourceColumn: Nome do Mês

		annotation SummarizationSetBy = Automatic

	column 'Ano mes num'
		dataType: int64
		formatString: 0
		lineageTag: dd034a1d-ca0f-46fe-bb90-3cd19aff49bc
		summarizeBy: sum
		sourceColumn: Ano mes num

		annotation SummarizationSetBy = Automatic

	partition 'pesquisa de nps' = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\home\OneDrive\Desktop\projetos\customer success\pesquisa de nps.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"ID Pesquisa NPS", Int64.Type}, {"ID Cliente", Int64.Type}, {"Data da Pesquisa", type date}, {"Pontuacao NPS (0-10)", Int64.Type}, {"Categoria", type text}}),
				    #"Ano Inserido" = Table.AddColumn(#"Tipo Alterado", "Ano", each Date.Year([Data da Pesquisa]), Int64.Type),
				    #"Texto Inserido Entre os Delimitadores" = Table.AddColumn(#"Ano Inserido", "Mes", each Text.BetweenDelimiters(Text.From([Data da Pesquisa], "pt-BR"), "/", "/"), type text),
				    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Texto Inserido Entre os Delimitadores", "Dia", each Text.BeforeDelimiter(Text.From([Data da Pesquisa], "pt-BR"), "/"), type text),
				    #"Nome do Mês Inserido" = Table.AddColumn(#"Texto Inserido Antes do Delimitador", "Nome do Mês", each Date.MonthName([Data da Pesquisa]), type text),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"Nome do Mês Inserido", "Ano mes num", each Text.Combine({Text.From([Ano], "pt-BR"), [Mes]}), type text),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida",{{"Ano mes num", Int64.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

